---

 - hosts: localhost
   remote_user: root
   gather_facts: true
   tasks:
     - name: check image exist or not
       command: "docker images -q tomcatkube:{{IMAGE_VERSION}}"
       register: found_image

     - debug: msg="{{found_image.stdout}}"

     - name: remove docker image
       command: "docker rmi -f tomcatkube:{{IMAGE_VERSION}}"
       when: found_image.stdout != ""

     - name: create docker image from docker file
       command: "docker build -t aditi/tomcatkube:{{IMAGE_VERSION}} ."
       register: docker_res
     - name: login to docker 
       command: "docker login --username aditiu --password {{DOCKER_PASSWORD}}"
     - name: push docker image 
       command: "docker push aditi/tomcatkube:{{IMAGE_VERSION}}"
  